name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.7

    - name: UDP Receive Buffer Size
      run: sudo sysctl -w net.core.rmem_max=2500000

    - name: Test
      run: go test -v ./...
    
    - name: Build
      run: make dscluster
